config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
 get '/', to: 'home#index', as: 'root'
 get 'home/index'
 get 'home/about'

 post '/' => 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :user, :optional => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stocks
          
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:id] == ""
      @nothing = "Please enter a valid symbol"
    elsif
      if params[:id]
        begin #error handling
          @stock = StockQuote::Stock.quote(params[:id])
        rescue StandardError #StandardError is optional
          @error = "That stock symbol doesn't exist .. please enter a valid symbol"
        end
      end
    end
  end

  def about

  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id)
    end

    def correct_user
      @ticker = current_user.stocks.find_by(id: params[:id])
      redirect_to stocks_path, notice: "Not Authorized to edit this stock" if @ticker.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
    <div class='alert alert-warning alert-dismissible'>
        <button class='close' data-dismiss='alert'>
            <i class='glyphicon glyphicon-remove-circle'></i>
            </button>
            <%= content_tag(:div, msg) %>
<% end %>


<%# or you can just paste these two following codes from Devise Docs %>
<%# <p class="notice"><%= notice %>
<%# <p class="alert"><%= alert %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  <%= link_to "HUNCHR", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <li><%= link_to "Home", root_path, class: "nav-item nav-link" %></li>
      <li><%= link_to "About Us", home_about_path, class: "nav-item nav-link" %></li>
    </div>
  </div>
  <div class="d-flex flex-row-reverse bd-highlight">
    <div class='navbar-nav p-2 bd-highlight'>
      <% if user_signed_in? %>
        <li><%= link_to "List Stocks", stocks_path, class: "nav-item nav-link" %></li>
        <li><%= link_to "Add New Stock", new_stock_path, class: "nav-item nav-link" %></li>
        <li><%= link_to "Update Profile", edit_user_registration_path, class: "nav-item nav-link" %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-item nav-link" %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path, class: "nav-item nav-link" %></li>
        <li><%= link_to "Log In", new_user_session_path, class: "nav-item nav-link" %></li>
      <% end %> 
    </div>
  </div>  
</nav>

app/views/home/about.html.erb
<h1>Play for free on Hunchr</h1>

app/views/home/index.html.erb
<h1>Hunchr Trading App</h1><br/><br/>
<div class="form-group">
    <%= form_tag root_path, :method => 'POST' do %>
        <%= text_field_tag 'id', nil, placeholder: "Enter Company Ticker Symbol", size: 50, class: 'form-control' %><br/><br/>
        <%= submit_tag "Look Up Stock Quote", class: 'btn btn-primary' %>
</div>
<% end %>


<br/><br/>

<% if @stock %>
    <strong>Company Name: </strong><%= @stock.company_name %> - <%= @stock.symbol %><br/>
    <strong>Listed on: </strong><%= @stock.primary_exchange %> <br/>
    <strong>Sector: </strong><%= @stock.sector %><br/>
    <strong>Closing Price: </strong><%= @stock.close %><br/>
    <strong>Day's high price: </strong><%= @stock.high %><br/>
    <strong>Day's low price: </strong><%= @stock.low %><br/>
    <strong>Volume: </strong><%= @stock.latest_volume %><br/>
    <strong>Market Capitalization: </strong><%= @stock.market_cap %><br/>
    <strong>Price Earning Ratio: </strong><%= @stock.pe_ratio %><br/>
    <strong>52-week High: </strong><%= @stock.week52_high %><br/>
    <strong>52-week Low: </strong><%= @stock.week52_low %><br/>
<% end %>

<% if @error %>
    <%= @error %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hunchr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <%= render 'home/flash' %>
    <%= yield %>
  
  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ticker %>
    <%= form.text_field :ticker %>
  </div>

  <div class="field">
    <%= form.text_field :user_id, value: current_user.id, type: 'hidden' %>
   </div>

  <div class="actions btn btn-danger">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<h1>Stocks</h1>

<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th>Ticker</th>
      <th>Current Price</th>
      <th>Company Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <% if stock.user_id == current_user.id %>
        <% begin %> 
          <% @stock_quote = StockQuote::Stock.quote(stock.ticker) %>
        <% rescue StandardError %>
          <tr>
          <td><%= stock.ticker %></td>
          <td><%= "N/A" %></td>
          <td><%= "N/A" %></td>
          <td><%= link_to 'Show', stock %></td>
          <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
          <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
        <tr>
          <td><%= stock.ticker %></td>
          <td><%= @stock_quote.close %></td>
          <td><%= @stock_quote.company_name %></td>
          <td><%= link_to 'Show', stock, class: 'btn btn-primary btn-sm' %></td>
          <td><%= link_to 'Edit', edit_stock_path(stock), class: 'btn btn-success btn-sm' %></td>
          <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
        </tr>
        <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path, class: 'btn btn-default' %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<% begin %> 
      <% @stock_quote = StockQuote::Stock.quote(@stock.ticker) %>
<% rescue StandardError %>
<% end %>

<div class='card'>
  <div class='card-header'>
    <h3 class='card-title'><strong><%= @stock_quote.company_name %> - <%= @stock_quote.symbol %></strong></h3>
  </div>
  <div class='card-body'>
    <h1><%= @stock_quote.close %></h1><br/><br/>
    <strong>Symbol: </strong><%= @stock_quote.symbol %> <br/>
    <strong>Listed on: </strong><%= @stock_quote.primary_exchange %> <br/>
    <strong>Sector: </strong><%= @stock_quote.sector %><br/>
    <strong>Closing Price: </strong><%= @stock_quote.close %><br/>
    <strong>Day's high price: </strong><%= @stock_quote.high %><br/>
    <strong>Day's low price: </strong><%= @stock_quote.low %><br/>
    <strong>Volume: </strong><%= @stock_quote.latest_volume %><br/>
    <strong>Market Capitalization: </strong><%= @stock_quote.market_cap %><br/>
    <strong>Price Earning Ratio: </strong><%= @stock_quote.pe_ratio %><br/>
    <strong>52-week High: </strong><%= @stock_quote.week52_high %><br/>
    <strong>52-week Low: </strong><%= @stock_quote.week52_low %><br/>
  </div>
  
</div><br/><br/>

<%= link_to 'Edit', edit_stock_path(@stock), class: 'btn btn-primary' %> |
<%= link_to 'Destroy', stock_path(@stock), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %> |
<%= link_to 'Back', stocks_path, class: 'btn btn-primary' %>